--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      Modulo2.DM1
-- Author :       InakyO
--
-- Date Created : Wednesday, January 18, 2023 23:07:37
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: ORDEN_COMPRA 
--

CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID      NUMBER(16, 0)    NOT NULL,
    FECHA_HORA           DATE             NOT NULL,
    DIRECCION_ENTREGA    VARCHAR2(200)    NOT NULL,
    TIPO_DE_PAGO         NUMBER(1, 0)     NOT NULL,
    TARJETA_ID           NUMBER(15, 0)    NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (ORDEN_COMPRA_ID)
)
;



-- 
-- TABLE: PAQUETERIA 
--

CREATE TABLE PAQUETERIA(
    PAQUETERIA_ID    NUMBER(2, 0)    NOT NULL,
    NOMBRE           VARCHAR2(40)    NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (PAQUETERIA_ID)
)
;



-- 
-- TABLE: FACTURA 
--

CREATE TABLE FACTURA(
    FACTURA_ID         NUMBER(10, 0)    NOT NULL,
    FOLIO              CHAR(6)          NOT NULL,
    COMISION           NUMBER(10, 2)    NOT NULL,
    ORDEN_COMPRA_ID    NUMBER(16, 0)    NOT NULL,
    PAQUETERIA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (FACTURA_ID), 
    CONSTRAINT RefORDEN_COMPRA29 FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID),
    CONSTRAINT RefPAQUETERIA30 FOREIGN KEY (PAQUETERIA_ID)
    REFERENCES PAQUETERIA(PAQUETERIA_ID)
)
;



-- 
-- TABLE: SUBASTA 
--

CREATE TABLE SUBASTA(
    SUBASTA_ID         NUMBER(10, 0)    NOT NULL,
    FECHA_HORA         DATE             NOT NULL,
    TOTAL_PRODUCTOS    NUMBER(4, 0)     NOT NULL,
    FECHA_CIERRE       DATE             NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (SUBASTA_ID)
)
;



-- 
-- TABLE: PRODUCTO_SUBASTA 
--

CREATE TABLE PRODUCTO_SUBASTA(
    PRODUCTO_SUBASTA_ID    NUMBER(15, 0)    NOT NULL,
    CALIFICACION           NUMBER(1, 0),
    PRODUCTO_ID            NUMBER(15, 0)    NOT NULL,
    OFERTA_GANADOR_ID      NUMBER(15, 0),
    SUBASTA_ID             NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID        NUMBER(16, 0),
    CONSTRAINT PK23 PRIMARY KEY (PRODUCTO_SUBASTA_ID), 
    CONSTRAINT RefORDEN_COMPRA43 FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID),
    CONSTRAINT RefSUBASTA31 FOREIGN KEY (SUBASTA_ID)
    REFERENCES SUBASTA(SUBASTA_ID)
)
;



-- 
-- TABLE: MONITOREO 
--

CREATE TABLE MONITOREO(
    PRODUCTO_SUBASTA_ID    NUMBER(15, 0)    NOT NULL,
    NUM_REGISTRO           NUMBER(2, 0)     NOT NULL,
    FECHA                  DATE             NOT NULL,
    LATITUD                NUMBER(10, 8)    NOT NULL,
    LONGITUD               NUMBER(11, 8)    NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (PRODUCTO_SUBASTA_ID, NUM_REGISTRO), 
    CONSTRAINT RefPRODUCTO_SUBASTA35 FOREIGN KEY (PRODUCTO_SUBASTA_ID)
    REFERENCES PRODUCTO_SUBASTA(PRODUCTO_SUBASTA_ID)
)
;



-- 
-- TABLE: PRODUCTO_COMENTARIO 
--

CREATE TABLE PRODUCTO_COMENTARIO(
    PRODUCTO_COMENTARIO_ID    NUMBER(15, 0)    NOT NULL,
    COMENTARIO                VARCHAR2(350)    NOT NULL,
    FECHA                     DATE             NOT NULL,
    PRODUCTO_SUBASTA_ID       NUMBER(15, 0)    NOT NULL,
    CONSTRAINT PK27 PRIMARY KEY (PRODUCTO_COMENTARIO_ID), 
    CONSTRAINT RefPRODUCTO_SUBASTA48 FOREIGN KEY (PRODUCTO_SUBASTA_ID)
    REFERENCES PRODUCTO_SUBASTA(PRODUCTO_SUBASTA_ID)
)
;



